### ISSUE TITLE
Companion satellite stop working with companion 2.2.1 

### ISSUE THREAD

**Issue by acroweb** [bitfocus/companion-module-skaarhoj-rawpanel#2]
Since I do the update of companion 2.2.1, the satellite function of the skaarhoj stops working with my master key one. The configuration still the same of the previous version (2.2.0).

**Comment by McHauge** [comment]
Hi @acroweb, did all of it just stop working or, only some of it?

Also what kind of setup are you running, is it the satellite v2 interface, or is it more based on use of the feedbacks?

**Comment by McHauge** [comment]
Another quick question, how is the skaarhoj device set up? Fully rawpanel, part of a unisketch config or in bluepill mode?

Just so i have something to test against.

The only real change should be that it now supports the toggle/latch functions in companion and that the manual/help file now loads the correct pictures.

But there might have been changes inside companion itself sice i made those fixes.

**Comment by acroweb** [comment]
Hello,
The satellite V2 option stop working, but the feedback and the other option are working. The skaarhoj is configured in full RawPanel and work well with the old version of companion. 
Thank you a lot.

**Comment by McHauge** [comment]
I'll give it a look tomorrow when I'm close to a panel, and see if o can get it working again.

Out of curiosity does it change behavior depending on what ip you tie companion to, like in the little popup, where you can select IP and port?

**Comment by McHauge** [comment]
quick note, this has not been forgotten, i just havent had the time yet

**Comment by acroweb** [comment]
Still suck with v2.4.1 of companion

**Comment by lundbergjohan** [comment]
Any news on this issue?
I'm also stuck on v 2.4.1 of Companion to have this working.
Would really prefer to be able to jump on v 3.x but need the Skaarhoj support and of course this bug fixed.

Let me know if there is anything I can do to help make this happen soon.

Thanks!

**Comment by lundbergjohan** [comment]
@McHauge 
Any chance this will happen anytime soon?

Thanks!

**Comment by McHauge** [comment]
> @McHauge 
> Any chance this will happen anytime soon?
> 
> Thanks!

It worked for me on the newest 2.x release, I have not been able to replicate it, have you tried it on your end?

**Comment by McHauge** [comment]
Hi, think I found the fix for use with newer versions of companion 2.x after the 2.2.0 version, please download the test build from here, marked with 2.4-stable-skaarhoj: https://1drv.ms/f/s!AtUYbExJseNtlK56tNfedSER8S7OvQ

**Comment by McHauge** [comment]
Updated Package with companion v2.4.2 and the SKAARHOJ module v1.0.4 is now available for windows on the link above :)

**Comment by McHauge** [comment]
Im gonna close this for now, as I have now both pused a fix for Companion 2.x and pushed the first 3.x compatible release of the core, if anything else pops up, please create a new ticket :)

**Comment by acroweb** [comment]
Hello, I have tested with the V3.1.1 of companion. With this new version, the problem seems half solved. The satelite mode works without a hitch, but the rest, with feedbacks and the ability to write on an lcd or adjust a led from a button, doesn't work. Am I the only one with this problem?
